// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __Countr_h__
#define __Countr_h__

#include "Countr_RcppExports.h"

#endif // __Countr_h__
